---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
          - name: POSTGRES_DB
            value: "xwiki"  # Replace with your PostgreSQL database name
          - name: POSTGRES_USER
            value: "xwiki"  # Replace with your PostgreSQL username
          - name: POSTGRES_PASSWORD
            value: "xwiki"  # Replace with your PostgreSQL password
        ports:
        - containerPort: 5432